esphome:
  name: "water-meter"
  platform: ESP8266
  board: nodemcuv2
     
  includes:
    - custom_components/izar_meter.h
  libraries:
    - SPI 
    - "https://github.com/maciekn/izar-wmbus-esp.git"
    - "https://github.com/knolleary/pubsubclient.git"
    - "https://github.com/bblanchon/ArduinoJson.git"

#esp8266:
#  board: nodemcuv2

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX"

ota:
  password: "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "WaterMeter-Esp8266"
    password: "XXXXXXXXXXXXXXXXXXXX"

captive_portal:

sensor:
- platform: custom
  lambda: |-
    auto my_sensor = new MyCustomSensor();
    App.register_component(my_sensor);
    return {my_sensor->water_sensor, my_sensor->id_sensor}; 
  sensors:
  - name: "Water meter consumtion"
    unit_of_measurement: l
    accuracy_decimals: 0
  - name: "Id licznika wody"
    accuracy_decimals: 0
