esphome:
  name: "water-meter"
  platform: ESP8266
  board: nodemcuv2
     
  includes:
    - custom_components/izar_meter.h
  libraries:
    - SPI 
    - "https://github.com/maciekn/izar-wmbus-esp.git"
    - "https://github.com/bblanchon/ArduinoJson.git"

#esp8266:
#  board: nodemcuv2

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX"

ota:
  password: "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "WaterMeter-Esp8266"
    password: "XXXXXXXXXXXXXXXXXXXX"

captive_portal:

text_sensor:
  - platform: custom
    lambda: |-
      auto textsensor = new MyTextSensor();
      App.register_component(textsensor);
      return {textsensor->my_text_sensor};
    text_sensors:
      - name: Meter ID                    #text HEX
        filters:
        - to_upper:

sensor:
  - platform: custom
    lambda: |-
      auto sensor = new MySensor();
      App.register_component(sensor);
      return {sensor->my_sensor};
    sensors:
      - name: Water meter state          #float value
        unit_of_measurement: L
        accuracy_decimals: 0
  - platform: dht                       #DHT22 sensor
    pin: D4                             #*****************use your pin***************************
    model: DHT22
    temperature:
      name: "Temperature"
    humidity:
      name: "Humidity"
    update_interval: 5s
