esphome:
  name: "water-meter"
  platform: ESP8266
  board: nodemcuv2
     
  includes:
    - custom_components/izar_meter.h
  libraries:
    - SPI 
    - "https://github.com/maciekn/izar-wmbus-esp.git"
    - "https://github.com/bblanchon/ArduinoJson.git"

#esp8266:
#  board: nodemcuv2

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX"

ota:
  password: "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "WaterMeter-Esp8266"
    password: "XXXXXXXXXXXXXXXXXXXX"

captive_portal:



text_sensor:
- platform: custom
  lambda: |-
    auto my_custom_sensor = new MyCustomSensor();
    App.register_component(my_custom_sensor);
    return {my_custom_sensor->water_sensor, my_custom_sensor->id_sensor};
  text_sensors:
  - name: "Water meter usage"
    filters:
    - append: " L"
  - name: "Water meter ID"

sensor:
- platform: dht
  pin: D4  							#*****************use your pin***************************
  model: DHT22
  temperature:
    name: "Temperature"
  humidity:
    name: Humidity"
  update_interval: 5s

